name: Mock API Lab CI

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      run_demo:
        description: 'Run interactive demo'
        required: false
        type: boolean
        default: false
  push:
    paths:
      - 'mock-api-lab/**'
      - '.github/workflows/mock-api-lab.yml'
  pull_request:
    paths:
      - 'mock-api-lab/**'

jobs:
  test-mock-api-lab:
    name: Test Mock API Lab
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: mock-api-lab/package-lock.json

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Display Node and npm versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        working-directory: mock-api-lab
        run: |
          npm install
          cd oauth-server && npm install && cd ..
          cd apim-simulator && npm install && cd ..

      - name: Start OAuth server in background
        working-directory: mock-api-lab/oauth-server
        run: |
          npm start &
          echo $! > oauth-server.pid
          sleep 3

      - name: Start APIM simulator in background
        working-directory: mock-api-lab/apim-simulator
        run: |
          npm start &
          echo $! > apim-simulator.pid
          sleep 3

      - name: Wait for services to be ready
        run: |
          echo "Waiting for OAuth server..."
          timeout 30 bash -c 'until curl -sf http://localhost:3001/health; do sleep 1; done'
          echo "✓ OAuth server is ready"

          echo "Waiting for APIM simulator..."
          timeout 30 bash -c 'until curl -sf http://localhost:8080/health; do sleep 1; done'
          echo "✓ APIM simulator is ready"

      - name: Verify services
        run: |
          echo "=== OAuth Server Status ==="
          curl -s http://localhost:3001/health | jq

          echo "=== APIM Simulator Status ==="
          curl -s http://localhost:8080/health | jq

      - name: Run tests
        working-directory: mock-api-lab/scripts
        run: |
          chmod +x test-api.sh
          ./test-api.sh

      - name: Run load test
        working-directory: mock-api-lab/scripts
        run: |
          chmod +x load-test.sh
          ./load-test.sh primary-key-12345 50

      - name: Test OAuth flow
        run: |
          echo "=== Testing OAuth Client Credentials Flow ==="
          TOKEN_RESPONSE=$(curl -s -X POST http://localhost:3001/oauth/token \
            -d 'grant_type=client_credentials' \
            -d 'client_id=application' \
            -d 'client_secret=secret')

          echo "Token Response:"
          echo "$TOKEN_RESPONSE" | jq

          TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.accessToken')

          if [ -z "$TOKEN" ] || [ "$TOKEN" == "null" ]; then
            echo "❌ Failed to get OAuth token"
            exit 1
          fi

          echo "✓ OAuth token obtained"

          echo "=== Testing Protected Resource Access ==="
          PROTECTED_RESPONSE=$(curl -s -H "Authorization: Bearer $TOKEN" \
            http://localhost:3001/api/protected)

          echo "$PROTECTED_RESPONSE" | jq

          if echo "$PROTECTED_RESPONSE" | jq -e '.message' | grep -q "Success"; then
            echo "✓ Protected resource access successful"
          else
            echo "❌ Protected resource access failed"
            exit 1
          fi

      - name: Test APIM subscription keys
        run: |
          echo "=== Testing APIM Without Subscription Key ==="
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/api/get)

          if [ "$HTTP_CODE" == "401" ]; then
            echo "✓ Correctly rejected request without subscription key (HTTP $HTTP_CODE)"
          else
            echo "❌ Expected HTTP 401, got HTTP $HTTP_CODE"
            exit 1
          fi

          echo "=== Testing APIM With Valid Subscription Key ==="
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Ocp-Apim-Subscription-Key: primary-key-12345" \
            http://localhost:8080/api/get)

          if [ "$HTTP_CODE" == "200" ]; then
            echo "✓ Successfully accessed API with subscription key (HTTP $HTTP_CODE)"
          else
            echo "❌ Expected HTTP 200, got HTTP $HTTP_CODE"
            exit 1
          fi

      - name: Test rate limiting
        run: |
          echo "=== Testing Rate Limiting ==="

          # Use secondary key with 10 req/min limit
          success=0
          rate_limited=0

          for i in {1..20}; do
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Ocp-Apim-Subscription-Key: secondary-key-67890" \
              http://localhost:8080/api/get)

            if [ "$HTTP_CODE" == "200" ]; then
              success=$((success + 1))
            elif [ "$HTTP_CODE" == "429" ]; then
              rate_limited=$((rate_limited + 1))
            fi

            sleep 0.1
          done

          echo "Success: $success, Rate Limited: $rate_limited"

          if [ $rate_limited -gt 0 ]; then
            echo "✓ Rate limiting is working (got $rate_limited rate-limited responses)"
          else
            echo "⚠ Warning: No rate limiting detected (this might be OK for quick tests)"
          fi

      - name: Check APIM stats
        run: |
          echo "=== APIM Statistics ==="
          curl -s http://localhost:8080/stats | jq

      - name: Run demo (if requested)
        if: ${{ inputs.run_demo }}
        working-directory: mock-api-lab/scripts
        run: |
          chmod +x demo.sh
          # Demo requires interactive input, so we'll skip actual execution in CI
          echo "Demo script is available at mock-api-lab/scripts/demo.sh"
          echo "Run locally with: cd mock-api-lab/scripts && ./demo.sh"

      - name: Cleanup
        if: always()
        run: |
          # Kill background processes
          if [ -f mock-api-lab/oauth-server/oauth-server.pid ]; then
            kill $(cat mock-api-lab/oauth-server/oauth-server.pid) 2>/dev/null || true
          fi
          if [ -f mock-api-lab/apim-simulator/apim-simulator.pid ]; then
            kill $(cat mock-api-lab/apim-simulator/apim-simulator.pid) 2>/dev/null || true
          fi

          # Fallback: kill by port
          lsof -ti:3001 | xargs kill -9 2>/dev/null || true
          lsof -ti:8080 | xargs kill -9 2>/dev/null || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: |
            mock-api-lab/**/*.log
          retention-days: 7
          if-no-files-found: ignore

  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test-mock-api-lab
    if: always()

    steps:
      - name: Check test results
        run: |
          echo "## Mock API Lab Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ All tests completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Components Tested" >> $GITHUB_STEP_SUMMARY
          echo "- OAuth 2.0 Server (Client Credentials + Password Grant)" >> $GITHUB_STEP_SUMMARY
          echo "- APIM Simulator (Subscription Keys + Rate Limiting)" >> $GITHUB_STEP_SUMMARY
          echo "- Integration Tests" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Quick Start" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'cd mock-api-lab' >> $GITHUB_STEP_SUMMARY
          echo './install.sh' >> $GITHUB_STEP_SUMMARY
          echo 'npm run start:all' >> $GITHUB_STEP_SUMMARY
          echo 'cd scripts && ./test-api.sh' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
